apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-test
  labels:
    app: gitops-test
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: gitops-test
  template:
    metadata:
      labels:
        deployment: gitops-test
    spec:
      containers:
        - name: gitops-test
          image: 'quay.io/jparsai/gitops-test:v3'
          env:
          - name: CREATE_CLUSTER_ROLE
            value: "true"
      serviceAccountName: "argocd-argocd-application-controller"
